require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable

Layout/HashAlignment:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/ArgumentAlignment:
  Enabled: false

Metrics/BlockLength:
  AllowedMethods: ["describe", "context"]
  Exclude:
    - "config/environments/development.rb"
    - "spec/rails_helper.rb"
    - "spec/spec_helper.rb"
    - "**/*.rake"

Rails/Output:
  Exclude:
    - "config/initializers/utilities/awesome_print.rb"

Metrics/AbcSize:
  Exclude:
    - "config/initializers/utilities/awesome_print.rb"

Style/FrozenStringLiteralComment:
  Exclude:
    - "db/migrate/*.rb"
    - "**/*.rake"
